# 참고: http://jasperreports.sourceforge.net/sample.reference/fonts/
# 참고: http://dev.classmethod.jp/server-side/java/jasperreports-tutorial/

net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.gulim=fonts/gulim.xml